apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa/podinfo.yaml
  - deployment/podinfo.yaml
  - service/podinfo.yaml
  - ingress/podinfo.yaml

images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: "6.3.4"
